### ISSUE TITLE
Conectivity

### ISSUE THREAD

**Issue by ThanhMelb** [o-snoopy-o/dbus-canbus-battery#1]
Hi, 
Thanks for the wonderfull project, i have followed the guide, make sure the cable is good and all steps are followed, but i have this error, do you know how to fix it?

root@einstein:~# python3 /opt/victronenergy/dbus-canbus-battery/dbus-canbus-battery.py
DEBUG:root:VeDbusTreeExport / has been created
DEBUG:root:VeDbusTreeExport /Mgmt has been created
DEBUG:root:added /Mgmt/ProcessName with start value /opt/victronenergy/dbus-canbus-battery/dbus-canbus-battery.py. Writeable is False
DEBUG:root:added /Mgmt/ProcessVersion with start value Unknown version, running on Python 3.8.18. Writeable is False
DEBUG:root:added /Mgmt/Connection with start value BMS-CAN. Writeable is False
DEBUG:root:added /DeviceInstance with start value 41. Writeable is False
DEBUG:root:added /ProductId with start value 47735. Writeable is False
DEBUG:root:added /ProductName with start value ELPM482-00005. Writeable is False
DEBUG:root:added /FirmwareVersion with start value 0. Writeable is False
DEBUG:root:added /HardwareVersion with start value 0. Writeable is False
DEBUG:root:added /Connected with start value 1. Writeable is False
DEBUG:root:VeDbusTreeExport /Info has been created
DEBUG:root:added /Info/MaxDischargeCurrent with start value 0.0. Writeable is False
DEBUG:root:added /Info/MaxChargeVoltage with start value 0.0. Writeable is False
DEBUG:root:added /Info/MaxChargeCurrent with start value 0.0. Writeable is False
DEBUG:root:added /Info/BatteryLowVoltage with start value 0.0. Writeable is False
DEBUG:root:added /Soc with start value 0. Writeable is False
DEBUG:root:added /Soh with start value 0. Writeable is False
DEBUG:root:VeDbusTreeExport /System has been created
DEBUG:root:added /System/StateOfHealth with start value 0. Writeable is False
DEBUG:root:VeDbusTreeExport /Dc has been created
DEBUG:root:VeDbusTreeExport /Dc/0 has been created
DEBUG:root:added /Dc/0/Voltage with start value 0.0. Writeable is False
DEBUG:root:added /Dc/0/Current with start value 0.0. Writeable is False
DEBUG:root:added /Dc/0/Power with start value 0.0. Writeable is False
DEBUG:root:added /Dc/0/Temperature with start value 0.0. Writeable is False
DEBUG:root:added /System/MinCellVoltage with start value 0.0. Writeable is False
DEBUG:root:added /System/MaxCellVoltage with start value 0.0. Writeable is False
DEBUG:root:added /System/MinCellTemperature with start value 0. Writeable is False
DEBUG:root:added /System/MaxCellTemperature with start value 0. Writeable is False
DEBUG:root:added /System/NrOfModulesOnline with start value 0. Writeable is False
DEBUG:root:added /System/NrOfModulesOffline with start value 0. Writeable is False
DEBUG:root:added /InstalledCapacity with start value 0.0. Writeable is False
DEBUG:root:added /Capacity with start value 0.0. Writeable is False
DEBUG:root:VeDbusTreeExport /Alarms has been created
DEBUG:root:added /Alarms/HighVoltage with start value 0. Writeable is False
DEBUG:root:added /Alarms/LowVoltage with start value 0. Writeable is False
DEBUG:root:added /Alarms/HighTemperature with start value 0. Writeable is False
DEBUG:root:added /Alarms/LowTemperature with start value 0. Writeable is False
DEBUG:root:added /Alarms/HighChargeCurrent with start value 0. Writeable is False
DEBUG:root:added /Alarms/HighDischargeCurrent with start value 0. Writeable is False
DEBUG:root:added /Alarms/HighChargeTemperature with start value 0. Writeable is False
DEBUG:root:added /Alarms/CellImbalance with start value 0. Writeable is False
Traceback (most recent call last):
  File "/opt/victronenergy/dbus-canbus-battery/dbus-canbus-battery.py", line 256, in <module>
    service = DbusBatteryService()
  File "/opt/victronenergy/dbus-canbus-battery/dbus-canbus-battery.py", line 77, in __init__
    self._dbusservice.register()
  File "/opt/victronenergy/dbus-canbus-battery/vedbus.py", line 91, in register
    self._dbusname = dbus.service.BusName(self.name, self._dbusconn, do_not_queue=True)
  File "/usr/lib/python3.8/site-packages/dbus/service.py", line 144, in __new__
    raise NameExistsException(name)
dbus.exceptions.NameExistsException: Bus name already exists: com.victronenergy.battery

Thanks

**Comment by o-snoopy-o** [comment]
Look like the service is either:
A) Already running, or
B) Another piece of software is already creating the battery path.


A) Check the that the service is not already running,
Run in putty: ps | grep dbus-canbus-battery.py
If it's already running check your remote console and look for the battery.

B) Remove the conflicting software or disable it. I'm guessing you've tried other pieces of software like dbus-serialbattery or dbus-mqtt-battery.
Let me know how you go.

**Comment by ThanhMelb** [comment]
Hi there,

You are correct that I had dbus-mqtt-battery installed previously. However, I ran the uninstall script to remove it. Now, I can see the device in the remote console, but there is no data being displayed.

I have double-checked and triple-checked the connections: the 7-8 pin side is plugged into the Victron, and the terminator is also connected.

When I run tail -n 50 /var/log/syslog, I get the following error:
tail: can't open '/var/log/syslog': No such file or directory
tail: no files

I also manually created the log folder at /opt/victronenergy/dbus-canbus-battery/, but the issue persists.

Thanks so much for your help.

Thanh

**Comment by ThanhMelb** [comment]
Thanks so much, all working now after updating the python.
Thank you

**Comment by o-snoopy-o** [comment]
sorry for my delayed response, I'm glad you got it working. Is it still working as expected?

**Comment by robfoo2015** [comment]
Hi Guys,

I'm still having problems but learning lots. I've figured my Victron is a multiplus-2gx which doesn't have the can.bus but rather the ve.can ports. I have read they are not the same, the ve.can runs at 250kbps whilst the Samsung talks at 500kbps. I believe the can.bus talks at 500kbps. Would this be my problem?

**Comment by o-snoopy-o** [comment]
Hello robfoo2015,
Can you try using the BMS-Can ports instead?
The VE-Bus ports are proprietary protocol and not compatible.

![Image](https://github.com/user-attachments/assets/0d4e9021-264c-492d-ba3f-f0edf10e4c83)

**Comment by robfoo2015** [comment]
My multiplus is the gx model which Victron have replaced the bus-can with ve-can. Sent from my iPhoneOn 31 Jan 2025, at 2:13 pm, Michael ***@***.***> wrote:﻿
Hello robfoo2015,
Can you try using the BMS-Can ports instead?
image.png (view on web)

**Comment by mediacut** [comment]
Hello, what about Samsung MS4843E101A? any suggestion how to map the Can messages?

**Comment by o-snoopy-o** [comment]
> Hello, what about Samsung MS4843E101A? any suggestion how to map the Can messages?

Hi mediacut, I cannot find any information at all on that battery module.
I can only suggest you login to your Cerbo or another device with can bus support and run can dump on the interface to see what messages if any are being sent by the battery module. If you can get some can messages, you can then cross reference to the register map for the ELPM482-00005 battery mapped by my solution. If they happen to be the same you might be in luck, otherwise without the can bus register map it will be near impossible to implement a solution.

**Comment by o-snoopy-o** [comment]
> My multiplus is the gx model which Victron have replaced the bus-can with ve-can. Sent from my iPhoneOn 31 Jan 2025, at 2:13 pm, Michael ***@***.***> wrote:﻿
> Hello robfoo2015,
> Can you try using the BMS-Can ports instead?
> image.png (view on web)
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Without a suitable interface I don't know how you'll get the data out, I recommend adding a CerboGX to communicate with the Multiplus over Ve.Can. The BMS.Can port on the Cerbo GX can be used to connect the battery BMS, in this case following my instructions on this repo will enable the BMS to communicate with the Cerbo GX and ultimately provide the functionality you require.

**Comment by Yarno069** [comment]
Hi Snoopy, 
I am trying to get past the Putty part of your list.
I have managed to login to the root of my Cerbo GX but after that the help page here
https://www.victronenergy.com/live/ccgx:root_access#enable_sshd_and_log_in 
doesn't seem to be helping from  "3.3 Enable sshd and log in", none of what it says seems to work or is referencing Linux, none of the keys lines find any file or directory
So when I go to WinSCP I cannot find the directory.
Any idea on what I can do?
Sorry I'm new to this type of computer workings.
Thanks.

**Comment by o-snoopy-o** [comment]
> Hi Snoopy, I am trying to get past the Putty part of your list. I have managed to login to the root of my Cerbo GX but after that the help page here https://www.victronenergy.com/live/ccgx:root_access#enable_sshd_and_log_in doesn't seem to be helping from "3.3 Enable sshd and log in", none of what it says seems to work or is referencing Linux, none of the keys lines find any file or directory So when I go to WinSCP I cannot find the directory. Any idea on what I can do? Sorry I'm new to this type of computer workings. Thanks.

You need to enable it in remote console, have you done that step?

![Image](https://github.com/user-attachments/assets/3dae774e-10d9-42b0-93d2-288e163551a1)

**Comment by Yarno069** [comment]
Yes, Remote support is on

Are any of these correct? Or am I meant to be putting something else in there?
![Image](https://github.com/user-attachments/assets/3a990c02-5c03-4a75-a8d2-f7c94baa693f)

**Comment by o-snoopy-o** [comment]
> Yes, Remote support is on
> 
> Are any of these correct? Or am I meant to be putting something else in there? ![Image](https://github.com/user-attachments/assets/3a990c02-5c03-4a75-a8d2-f7c94baa693f)

I can't say from the attached image.
I take it your cerbo gx is at that ip address?
what happens when you connect in putty and winscp?
share screenshots.

**Comment by o-snoopy-o** [comment]
> Yes, Remote support is on
> 
> Are any of these correct? Or am I meant to be putting something else in there? ![Image](https://github.com/user-attachments/assets/3a990c02-5c03-4a75-a8d2-f7c94baa693f)

message me on reddit and i can offer help more easily. https://www.reddit.com/user/Sn-00-p/

**Comment by Yarno069** [comment]
![Image](https://github.com/user-attachments/assets/684c2db7-0a4e-40f3-b1bc-7b18db93e852)

![Image](https://github.com/user-attachments/assets/019ac093-2b28-4434-87f5-49e62b5fddf8)

![Image](https://github.com/user-attachments/assets/5e7bdb28-dc3c-4082-8b46-d024d033febf)

![Image](https://github.com/user-attachments/assets/b61bdd54-994d-4bc3-b0fb-4342e2c2b575)

![Image](https://github.com/user-attachments/assets/0648f1be-cce1-445e-ad9f-2305e2ba6819)

**Comment by o-snoopy-o** [comment]
you need to connect to the cerbo, your winscp is not connected to cerbo.
go tabs>new tab
enter the details and login.

![Image](https://github.com/user-attachments/assets/30ff1b2f-da48-4f6a-9da9-e1c91e93e2ee)

**Comment by Yarno069** [comment]
> you need to connect to the cerbo, your winscp is not connected to cerbo. go tabs>new tab enter the details and login.
> 
> ![Image](https://github.com/user-attachments/assets/30ff1b2f-da48-4f6a-9da9-e1c91e93e2ee)

Awesome, thank you. Hopefully I'll be right now. Cheers.

**Comment by Yarno069** [comment]
Ok, so I have what I think is working is the Cerbo GX, it is now displaying the battery, but the doesn't seem to be any communication to the battery.

![Image](https://github.com/user-attachments/assets/ac38addb-c30a-4318-bae0-8d511f1ae7b6)

I have checked the cable I made to confirm the connections 1 goes to 7, 2 goes to 8, 3 to 3. I have it plugged into VE.Can 1 and a 120Ω in the second port, other end into CN7 with switch on. Cerbo says it's connected even when unplugged.
I went through all the Protocol ID settings in the manual, still nothing. What could I be doing wrong?

![Image](https://github.com/user-attachments/assets/c768e93f-27a4-4949-8637-ac78d9585f1d)

![Image](https://github.com/user-attachments/assets/260e46fa-8579-42fa-8a8b-ae26b749e5f1)

**Comment by o-snoopy-o** [comment]
You haven't confirmed if your tried to candump. if can1 doesn't work try can0.
all that stuff below is canbus messages.

![Image](https://github.com/user-attachments/assets/e24a994e-29b1-4b39-9b4e-3106e03e98c6)

**Comment by o-snoopy-o** [comment]
> I have it plugged into VE.Can 1

Wrong, it needs to go into BMS.Can, this is from my guide: "Ensure that you have the CANBUS cable connected to the BMS and the Cerbo GX. The port on the Cerbo GX is the BMS-CAN."

**Comment by Yarno069** [comment]
Hi Michael,

I have plugged it into VE.Bus and still nothing. The other ports are called VE.Can 1 and VE.Can 2, tried can 2 as well.
I cannot get candump to show me anything or even work.

![Image](https://github.com/user-attachments/assets/5397fe5b-3be6-45cf-99f0-d269261f5880)

![Image](https://github.com/user-attachments/assets/4e0601bf-643c-44fe-85e6-2ac1750f6aa0)

![Image](https://github.com/user-attachments/assets/5366064c-2560-4f27-8992-9e80a4d3980e)

![Image](https://github.com/user-attachments/assets/d2750914-ec9d-499e-988c-7d081d54b80c)

**Comment by Yarno069** [comment]
Ok, found this and tried changing the VE.Can port 2 to CAN-Bus BMS LV (500 kbit/s) and now I get coms. on candump

![Image](https://github.com/user-attachments/assets/fdde359b-e6fb-4ec5-a8df-1f4d0704fd21)

![Image](https://github.com/user-attachments/assets/259d9dcc-eff5-4feb-a3e6-50d4538c3b43)
Still not sure about the rest of the stuff nowiresfil did, will have to have a look as it still isn't showing the info. I did try the CAN-Bus BMS HV (500 kbit/s) as well. I'm guessing these are newer Cerbo GX with changes to hardware. I picked VE.Can 2 so it would be close to can1 but I guess your program refers to can1 and not vecan1

**Comment by Yarno069** [comment]
Now I have made changes with notepad to dbus-canbus-battery.py changed CAN port from can1->vecan1
Also changed can-mappings.json, changed all the  100 to 500, 101 to 501 etc. and rebooted.
I am still not displaying the battery though...

**Comment by Yarno069** [comment]
Hi Michael,

Sorry to be annoying.

So I think I'm having trouble with the below because all the values are 0 and it's saying writable is false.
I think I'm also having trouble with dbus-canbus-battery.py starting because I has to manually start it twice before it would show up with grep, I have the root file in the /var/spool/cron folder, have been over eveything a few times to make sure it is correct, also using nowiresfil https://github.com/o-snoopy-o/dbus-canbus-battery/issues/3#issue-2855301644 information as the CAN looks like his.
Any idea what I'm doing wrong.
Thanks.

ps | grep dbus-canbus-battery.py
  732 root     31156 S    python3 /opt/victronenergy/dbus-canbus-battery/dbus-canbus-battery.py
14465 root      2692 S    grep dbus-canbus-battery.py
root@einstein:~# python3 /opt/victronenergy/dbus-canbus-battery/dbus-canbus-battery.py
DEBUG:root:VeDbusTreeExport / has been created
DEBUG:root:VeDbusTreeExport /Mgmt has been created
DEBUG:root:added /Mgmt/ProcessName with start value /opt/victronenergy/dbus-canbus-battery/dbus-canbus-battery.py. Writeable is False
DEBUG:root:added /Mgmt/ProcessVersion with start value Unknown version, running on Python 3.8.18. Writeable is False
DEBUG:root:added /Mgmt/Connection with start value BMS-CAN. Writeable is False
DEBUG:root:added /DeviceInstance with start value 41. Writeable is False
DEBUG:root:added /ProductId with start value 47735. Writeable is False
DEBUG:root:added /ProductName with start value ELPM482-00005. Writeable is False
DEBUG:root:added /FirmwareVersion with start value 0. Writeable is False
DEBUG:root:added /HardwareVersion with start value 0. Writeable is False
DEBUG:root:added /Connected with start value 1. Writeable is False
DEBUG:root:VeDbusTreeExport /Info has been created
DEBUG:root:added /Info/MaxDischargeCurrent with start value 0.0. Writeable is False
DEBUG:root:added /Info/MaxChargeVoltage with start value 0.0. Writeable is False
DEBUG:root:added /Info/MaxChargeCurrent with start value 0.0. Writeable is False
DEBUG:root:added /Info/BatteryLowVoltage with start value 0.0. Writeable is False
DEBUG:root:added /Soc with start value 0. Writeable is False
DEBUG:root:added /Soh with start value 0. Writeable is False
DEBUG:root:VeDbusTreeExport /System has been created
DEBUG:root:added /System/StateOfHealth with start value 0. Writeable is False
DEBUG:root:VeDbusTreeExport /Dc has been created
DEBUG:root:VeDbusTreeExport /Dc/0 has been created
DEBUG:root:added /Dc/0/Voltage with start value 0.0. Writeable is False
DEBUG:root:added /Dc/0/Current with start value 0.0. Writeable is False
DEBUG:root:added /Dc/0/Power with start value 0.0. Writeable is False
DEBUG:root:added /Dc/0/Temperature with start value 0.0. Writeable is False
DEBUG:root:added /System/MinCellVoltage with start value 0.0. Writeable is False
DEBUG:root:added /System/MaxCellVoltage with start value 0.0. Writeable is False
DEBUG:root:added /System/MinCellTemperature with start value 0. Writeable is False
DEBUG:root:added /System/MaxCellTemperature with start value 0. Writeable is False
DEBUG:root:added /System/NrOfModulesOnline with start value 0. Writeable is False
DEBUG:root:added /System/NrOfModulesOffline with start value 0. Writeable is False
DEBUG:root:added /InstalledCapacity with start value 0.0. Writeable is False
DEBUG:root:added /Capacity with start value 0.0. Writeable is False
DEBUG:root:VeDbusTreeExport /Alarms has been created
DEBUG:root:added /Alarms/HighVoltage with start value 0. Writeable is False
DEBUG:root:added /Alarms/LowVoltage with start value 0. Writeable is False
DEBUG:root:added /Alarms/HighTemperature with start value 0. Writeable is False
DEBUG:root:added /Alarms/LowTemperature with start value 0. Writeable is False
DEBUG:root:added /Alarms/HighChargeCurrent with start value 0. Writeable is False
DEBUG:root:added /Alarms/HighDischargeCurrent with start value 0. Writeable is False
DEBUG:root:added /Alarms/HighChargeTemperature with start value 0. Writeable is False
DEBUG:root:added /Alarms/CellImbalance with start value 0. Writeable is False
Traceback (most recent call last):
  File "/opt/victronenergy/dbus-canbus-battery/dbus-canbus-battery.py", line 256, in <module>
    service = DbusBatteryService()
  File "/opt/victronenergy/dbus-canbus-battery/dbus-canbus-battery.py", line 77, in __init__
    self._dbusservice.register()
  File "/opt/victronenergy/dbus-canbus-battery/vedbus.py", line 91, in register
    self._dbusname = dbus.service.BusName(self.name, self._dbusconn, do_not_queue=True)
  File "/usr/lib/python3.8/site-packages/dbus/service.py", line 144, in __new__
    raise NameExistsException(name)
dbus.exceptions.NameExistsException: Bus name already exists: com.victronenergy.battery
root@einstein:~#

**Comment by o-snoopy-o** [comment]
try changing this line in the dbus-canbus-battery.py file. Notice i added ".canbusbattery" behind the existing.
Use WinSCP to open the file, make the change then click save.
After that, issue reboot command in putty.
It takes a while for the service to start after reboot so give it 5 minutes then check the service is running. then go into the remote console and wait for it to show on overview or go into devices then to the battery. report back.

```
 Initialize the D-Bus service with register=False
        self._dbusservice = VeDbusService('com.victronenergy.battery.canbusbattery, register=False)
```

**Comment by Yarno069** [comment]
Ok so now I don't see anything on the GX Touch, no battery, before it had the battery but everything is zero.

This is also showing this

![Image](https://github.com/user-attachments/assets/89a4ef1c-d9d5-41ba-a2ea-fd658fe9adf4)

Then manually starting doesn't work

![Image](https://github.com/user-attachments/assets/1174ab04-4185-45e4-89f5-3791c47e5428)

Is this the correct Python?

![Image](https://github.com/user-attachments/assets/a6b4841d-daea-47e1-b504-8fe45768098b)

**Comment by Yarno069** [comment]
> Ok so now I don't see anything on the GX Touch, no battery, before it had the battery but everything is zero.
> 
> This is also showing this
> 
> ![Image](https://github.com/user-attachments/assets/89a4ef1c-d9d5-41ba-a2ea-fd658fe9adf4)
> 
> Then manually starting doesn't work
> 
> ![Image](https://github.com/user-attachments/assets/1174ab04-4185-45e4-89f5-3791c47e5428)
> 
> Is this the correct Python?
> 
> ![Image](https://github.com/user-attachments/assets/a6b4841d-daea-47e1-b504-8fe45768098b)

Ok, I changed it back and now

![Image](https://github.com/user-attachments/assets/3afc2c5c-adec-47df-b385-dbfe2a81fecd)

**Comment by o-snoopy-o** [comment]
you don't need to manually start it if all the other bits are done, it will start itself after some minutes. in your remote console have you set the battery monitor to be the batteries? System Setup > Battery Monitor.

![Image](https://github.com/user-attachments/assets/e00df7e9-49fe-4531-ac07-e9bd11d12639)

Have you gone to debug and check that the batteries are reporting onto dbus?
Debug > Values > Battery > 41 > .........

Also, changing back to the original code probably didn't help. you need to make small changes and debug each step. you'll confuse yourself really quickly. Not knowing how many changes you've now made makes it difficult to predict what is going on.

leave this change implemented as is: 

```
Initialize the D-Bus service with register=False
        self._dbusservice = VeDbusService('com.victronenergy.battery.canbusbattery, register=False)
```

This is the exact code i am running right now as a test to see whether i can release it. I have had some issues with the battery not reporting since the last update and i'm looking into whether this will fix it. I have had it running all day with no issues yet so will continue through some reboots of the Cerbo GX to test some more.


Side question, have you got a multiplus 2 connected? Have you configured it and got it working yet? Mine is fully working so not sure if that has anything to do with it.

**Comment by Yarno069** [comment]
Yes it comes up automatically but has no information. It was working like this before, that's why I changed it back.

I don't understand Debug > Values > Battery > 41 > .........   I have CAN comms

![Image](https://github.com/user-attachments/assets/11d27641-cc2e-4997-ba9b-d8760b5fb3a8)

I don't have the Multiplus yet, just GX Cerbro, GX Touch 50, and one of the ELEPM482-00005 batteries connected.

**Comment by o-snoopy-o** [comment]
> I don't understand Debug > Values > Battery > 41 > ......... I have CAN comms

you need to navigate through the remote console to find that.

FYI, this is what I decoded from your CAN data screenshot.
Don't worry too much about the figures that seem incorrect, they will probably come to a normal level after more data is captured and averaged.
![Image](https://github.com/user-attachments/assets/7fccc416-d66a-42c3-b0b9-53332bd6f64a)

I sent you a message on reddit offering to troubleshoot for you, reply if you want to go from there.
